

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lc_system_pro
    username: postgres
    password: umar2308
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  files:
    baseFolder: /files

